### ISSUE TITLE
JN5168-001-M00Z eagle library

### ISSUE THREAD

**Issue by ThomArmax** [Beerlesklopfer/JN5168-Bee#1]
Hi,

I would like to know if you could provide the JN5168-001-M00Z module library (symboles and footprint) for eagle. I have just purchased one of these modules, and I would like to make a breakout (breadboard friendly) PCB to test this module.

Thanks by advance

Best regards

Thomas

**Comment by Beerlesklopfer** [comment]
Hi Thomas,

 

I have those modules available here. I don't use that module any longer Do you want to have some?

 

Best regards

 

Joerg

 
 

Gesendet: Donnerstag, 30. April 2020 um 18:43 Uhr
Von: "Thomas COIN" <notifications@github.com>
An: "Beerlesklopfer/JN5168-Bee" <JN5168-Bee@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [Beerlesklopfer/JN5168-Bee] JN5168-001-M00Z eagle library (#1)


 

Hi,

I would like to know if you could provide the JN5168-001-M00Z module library (symboles and footprint) for eagle. I have just purchased one of these modules, and I would like to make a breakout (breadboard friendly) PCB to test this module.

Thanks by advance

Best regards

Thomas

**Comment by ThomArmax** [comment]
@Beerlesklopfer Thanks, that could be nice, but what I'm looking for is the eagle lib for jn5168 to design my own PCB :)
I have been browsing the web for hours ... I only found for KiCad

**Comment by Beerlesklopfer** [comment]
... here it is! ...


 

Be blessed!

 

Gesendet: Donnerstag, 30. April 2020 um 19:32 Uhr
Von: "Thomas COIN" <notifications@github.com>
An: "Beerlesklopfer/JN5168-Bee" <JN5168-Bee@noreply.github.com>
Cc: "Jörg Bernau" <Joerg.Bernau@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [Beerlesklopfer/JN5168-Bee] JN5168-001-M00Z eagle library (#1)


 

@Beerlesklopfer Thanks, that could be nice, but what I'm looking for is the eagle lib for jn5168 to design my own PCB :)
I have been browsing the web for hours ... I only found for KiCad

**Comment by ThomArmax** [comment]
Deer @Beerlesklopfer ,
Sorry to bother you, I have not received it. If you want, you can send it directly at `esvcorp[at]gmail[dot]com` , maybe attachment doesn't work when replying to GitHub issue by email.

Thanks by advance.

Best regards

Thom

**Comment by ThomArmax** [comment]
Hi,
I finally requested the the Eagle lib to to distributor I bought the module :)
Thanks.
Have a nice weekend
